spring.application.name=user-service

server.port=${USER_SERVICE_PORT:8100}

# Connecting to postgres DB for storing User details (use env for this)
spring.r2dbc.url=r2dbc:postgresql://${USER_DB_HOST:localhost}:${USER_DB_PORT:5432}/${USER_DB_NAME:UserDB}
spring.r2dbc.username=${USER_DB_USERNAME:postgres}
spring.r2dbc.password=${USER_DB_PASSWORD:1234}

# Force Spring to run schema.sql at startup
spring.sql.init.mode=always
# Continue even if a table already exists (prevents crash on 2nd run)
spring.sql.init.continue-on-error=false

# JWT secret keys (Remove from here and use env)
jwt.secret=${JWT_SECRET:ksfjhfsklelkfjseajwlfiohiholdaiholdghjbkvhoawuqpieopwnmcadjaklvbnmbakjelhquiyllidhajkbcjkahgdhauhauiiohlioawhdvfjhkoksfjhfsklelkfjseajwlfiohiholdaiholdghjbkvhoawuqpieopwnmcadjaklvbnmbakjelhquiyllidhajkbcjkahgdhauhauiiohlioawhdvfjhkoksfjhfsklelkfjseajwlfioh}
# Expires after (set to 1 day for now 1000 * 60 * 60 * 24)
jwt.expiration=${JWT_EXPIRATION:86400000}

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

# Monitoring config
# Expose health and metrics endpoints
management.endpoints.web.exposure.include=health,metrics,prometheus,info
# Show full health details (disk space, db status, etc.)
management.endpoint.health.show-details=always