spring.application.name=Auth-Service

server.port=${SERVER_PORT:8100}

# Connecting to postgres DB for storing User details (use env for this)
spring.r2dbc.url=${DB_URL:r2dbc:postgresql://localhost:5432/AuthServiceDB}
spring.r2dbc.username=${DB_USERNAME:postgres}
spring.r2dbc.password=${DB_PASSWORD:1234}

# Force Spring to run schema.sql at startup
spring.sql.init.mode=always
# Continue even if a table already exists (prevents crash on 2nd run)
spring.sql.init.continue-on-error=true

# JWT secret keys (Remove from here and use env)
#JWT_SECRET=ksfjhfsklelkfjseajwlfiohiholdaiholdghjbkvhoawuqpieopwnmcadjaklvbnmbakjelhquiyllidhajkbcjkahgdhauhauiiohlioawhdvfjhkoksfjhfsklelkfjseajwlfiohiholdaiholdghjbkvhoawuqpieopwnmcadjaklvbnmbakjelhquiyllidhajkbcjkahgdhauhauiiohlioawhdvfjhkoksfjhfsklelkfjseajwlfioh
# Expires after (set to 1 day for now 1000 * 60 * 60 * 24)
#JWT_EXPIRATION=86400000

# Monitoring config
# Expose health and metrics endpoints
management.endpoints.web.exposure.include=health,metrics,prometheus,info
# Show full health details (disk space, db status, etc.)
management.endpoint.health.show-details=always

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka