spring.application.name=auction-storage-service

server.port=${SERVER_PORT_PERSISTENCE_SERVICE:8090}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:AuctionStorageDB}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.instance.prefer-ip-address=true
#eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
