spring.application.name=auction-storage-service

server.port=${SERVER_PORT_STORAGE:8090}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:AuctionStorageDB}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.instance.prefer-ip-address=true
#eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

# RabbitMQ settings (using defaults for local deploy)
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

rabbitmq.queue.auction.creation=${RABBITMQ_QUEUE_AUCTION_CREATION:q.storage-service.auction.created}
rabbitmq.queue.auction.expire=${RABBITMQ_QUEUE_AUCTION_EXPIRE:q.auction-service.auction.expire}
rabbitmq.queue.auction.status.update=${RABBITMQ_QUEUE_AUCTION_STATUS_UPDATE:q.storage-service.auction.status.update}
rabbitmq.queue.auction.update=${RABBITMQ_QUEUE_AUCTION_UPDATE:q.storage-service.auction.update}
rabbitmq.queue.bid.placed=${RABBITMQ_QUEUE_BID_PLACED:q.storage-service.bid.placed}
