spring.application.name=auction-service

server.port=${SERVER_PORT_AUCTION:8200}

# Redis connection (use env)
spring.data.redis.host=${AUCTION_REDIS_HOST:localhost}
spring.data.redis.port=${AUCTION_REDIS_PORT:6379}
spring.data.redis.username=${AUCTION_REDIS_USERNAME:default}
spring.data.redis.password=${AUCTION_REDIS_PASSWORD:1234}

eureka.instance.prefer-ip-address=true
#eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# RabbitMQ settings (using defaults for local deploy)
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

rabbitmq.queue.name=queue_demo
rabbitmq.exchange.name=exchange_demo
rabbitmq.routing-key=routing_key_demo