spring.application.name=auction-service

server.port=${SERVER_PORT_AUCTION:8200}

# Redis connection (use env)
spring.data.redis.host=${AUCTION_REDIS_HOST:localhost}
spring.data.redis.port=${AUCTION_REDIS_PORT:6379}
spring.data.redis.username=${AUCTION_REDIS_USERNAME:default}
spring.data.redis.password=${AUCTION_REDIS_PASSWORD:1234}

eureka.instance.prefer-ip-address=true
#eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka