spring:
  application:
    name: API-Gateway-Service
  cloud:
    gateway:
      server:
        webflux:
          routes: # Custom routing added here

            #         -----Routing for User Service Admin endpoint-----
            - id: Auth-Admin-Service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/admin/**
              filters:
                - AuthenticationFilter
                - name: RoleFilter
                  args:
                    requiredRole: "ROLE_ADMIN"

            #         -----Routing for User Service public endpoints-----
            - id: Auth-Public-Service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@perIPKeyResolver}" # set ket resolver for endpoint(perIPKeyResolver or perJWTKeyResolver)
                    redis-rate-limiter.replenishRate: 3 # no. of tokens added to the bucket every second
                    redis-rate-limiter.burstCapacity: 3 # Maximum tokens the bucket can hold (burst capacity)


            - id: User-Service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user/**
              filters:
                - AuthenticationFilter
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@perIPKeyResolver}"
                    redis-rate-limiter.replenishRate: 3
                    redis-rate-limiter.burstCapacity: 3

#              - id: Auction-Service
#                uri: lb://AUCTION-SERVICE
#                predicates:
#                  - Path=/auction/**
#          discovery:
#            locator:
#              enabled: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    metrics:
      enabled: true
    configs:
      default:
        registerHealthIndicator: true
        allowHealthIndicatorToFail: true