spring.application.name=gateway-service

server.port=${GATEWAY_SERVICE_PORT:8000}

#JWT secret keys
jwt.secret=${JWT_SECRET:ksfjhfsklelkfjseajwlfiohiholdaiholdghjbkvhoawuqpieopwnmcadjaklvbnmbakjelhquiyllidhajkbcjkahgdhauhauiiohlioawhdvfjhkoksfjhfsklelkfjseajwlfiohiholdaiholdghjbkvhoawuqpieopwnmcadjaklvbnmbakjelhquiyllidhajkbcjkahgdhauhauiiohlioawhdvfjhkoksfjhfsklelkfjseajwlfioh}
# Expires after (set to 5 day as default 1000 * 60 * 60 * 24 * 5 = 432,000,000)
jwt.expiration=${JWT_EXPIRATION:432000000}

# Redis connection
spring.data.redis.host=${RATE_LIMIT_REDIS_HOST:localhost}
spring.data.redis.port=${RATE_LIMIT_REDIS_PORT:6379}
spring.data.redis.password=${RATE_LIMIT_REDIS_PASSWORD:1234}
spring.data.redis.username=${RATE_LIMIT_REDIS_USERNAME:default}

# Logging config
logback.log.file.path=./logs/test
# Show only warnings and errors from the framework
logging.level.org.springframework.cloud.gateway=WARN
# Keep custom logic at INFO or DEBUG to see Upstream/Downstream logs
logging.level.com.server.gateway=INFO

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}