spring:
  application:
    name: API-Gateway-Service
  cloud:
    gateway:
      server:
        webflux:
          routes: # Custom routing added here

#         -----Routing for service A----- Routing filters for SERVICE A are done using Java code in GatewayResilianceConfig
#              - id: SERVICE-A # Give a name to the service
#                uri: lb://SERVICE-A # Use the name of the service found in the Eureka Dashboard
#                predicates:
#                  - Path=/demo/** # Route certain endpoints to the service
#                filters:
#                  - RewritePath=/demo/(?<segment>.*), /$\{segment}
#                  # Filter the endpoint to only pass the routed endpoint to the service without the base
#                  - name: RequestRateLimiter
#                    args:
#                      key-resolver: "#{@userKeyResolver}"
#                      redis-rate-limiter.replenishRate: 3 # no. of tokens added to the bucket every second
#                      redis-rate-limiter.burstCapacity: 3 # Maximum tokens the bucket can hold (burst capacity)
#                      redis-rate-limiter.requestedTokens: 1 # no. tokens each request costs
#                  - AuthenticationFilter # Apply auth filter with role to routes
#                  - name: RoleFilter
#                    args:
#                      requiredRole: "ROLE_USER"

#         -----Routing for Auth Service Admin endpoint-----
              - id: Auth-Admin-Service
                uri: lb://AUTH-SERVICE
                predicates:
                  - Path=/auth/admin/**
                filters:
                  - AuthenticationFilter
                  - name: RoleFilter
                    args:
                      requiredRole: "ROLE_ADMIN"

#         -----Routing for Auth Service public endpoints-----
              - id: Auth-Public-Service
                uri: lb://AUTH-SERVICE
                predicates:
                  - Path=/auth/**
                filters:
                  - name: RequestRateLimiter
                    args:
                      key-resolver: "#{@perIPKeyResolver}" # set ket resolver for endpoint(perIPKeyResolver or perJWTKeyResolver)
                      redis-rate-limiter.replenishRate: 3 # no. of tokens added to the bucket every second
                      redis-rate-limiter.burstCapacity: 3 # Maximum tokens the bucket can hold (burst capacity)

#          discovery:
#            locator:
#              enabled: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    metrics:
      enabled: true
    configs:
      default:
        registerHealthIndicator: true
        allowHealthIndicatorToFail: true