spring.application.name=DiscoveryService

server.port=${SERVER_PORT:8761}

eureka.instance.hostname=${EUREKA_HOSTNAME:discovery-service}
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

# Monitoring config
# Expose health and metrics endpoints
management.endpoints.web.exposure.include=health,metrics,prometheus,info
# Show full health details (disk space, db status, etc.)
management.endpoint.health.show-details=always